//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DARP.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DARP.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solution has been exported succesfully.
        /// </summary>
        internal static string CSV_EXPORT_SUCCESFULLY {
            get {
                return ResourceManager.GetString("CSV_EXPORT_SUCCESFULLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has ocurred exporting CSV file.
        /// </summary>
        internal static string ERROR_EXPORTING_CSV {
            get {
                return ResourceManager.GetString("ERROR_EXPORTING_CSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is not DARP instances in the folder selected..
        /// </summary>
        internal static string ERROR_LOADING_NOT_INSTANCES {
            get {
                return ResourceManager.GetString("ERROR_LOADING_NOT_INSTANCES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has ocurred loading DARP instances. Error DARP files..
        /// </summary>
        internal static string ERROR_PROBLEMS_LOADED {
            get {
                return ResourceManager.GetString("ERROR_PROBLEMS_LOADED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A problem has ocurred during the execution of the algorithm..
        /// </summary>
        internal static string HEURISTIC_EXECUTED_FAIL {
            get {
                return ResourceManager.GetString("HEURISTIC_EXECUTED_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Algorithm has been executed succesfully..
        /// </summary>
        internal static string HEURISTIC_EXECUTED_SUCCESFULLY {
            get {
                return ResourceManager.GetString("HEURISTIC_EXECUTED_SUCCESFULLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} DARP instances have been loaded..
        /// </summary>
        internal static string PROBLEMS_LOADED {
            get {
                return ResourceManager.GetString("PROBLEMS_LOADED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Root path is empty. Please, select default path in settings..
        /// </summary>
        internal static string PROBLEMS_WARNING {
            get {
                return ResourceManager.GetString("PROBLEMS_WARNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has ocurred saving settings configuration.
        /// </summary>
        internal static string SETTINGS_ERROR_SAVING {
            get {
                return ResourceManager.GetString("SETTINGS_ERROR_SAVING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings have been saved succesfully..
        /// </summary>
        internal static string SETTINGS_SAVED_SUCCESFULLY {
            get {
                return ResourceManager.GetString("SETTINGS_SAVED_SUCCESFULLY", resourceCulture);
            }
        }
    }
}
